import org.apache.commons.codec.language.bm.Languages;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class Zadanie7 extends TestBase {


  @Test
  public void litecartTest() {
    driver.get("http://localhost:8090/litecart/admin/login.php");
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("admin");
    driver.findElement(By.name("login")).click();
   driver.findElement(By.linkText("Appearence")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Template");
    driver.findElement(By.linkText("Template")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Template");
    driver.findElement(By.linkText("Logotype")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Logotype");
   driver.findElement(By.linkText("Catalog")).click();
  assertEquals(driver.findElement(By.tagName("h1")).getText(), "Catalog");
    WebElement selected = driver.findElement(By.className("selected"));
    selected.findElement(By.linkText("Catalog")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Catalog");
    driver.findElement(By.linkText("Product Groups")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Product Groups");
    driver.findElement(By.linkText("Option Groups")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Option Groups");
    driver.findElement(By.linkText("Manufacturers")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Manufacturers");
    driver.findElement(By.linkText("Suppliers")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Suppliers");
    driver.findElement(By.linkText("Delivery Statuses")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Delivery Statuses");
    driver.findElement(By.linkText("Sold Out Statuses")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Sold Out Statuses");
    driver.findElement(By.linkText("Quantity Units")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Quantity Units");
    driver.findElement(By.linkText("CSV Import/Export")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "CSV Import/Export");

    driver.findElement(By.linkText("Countries")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Countries");
    driver.findElement(By.linkText("Currencies")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Currencies");
    driver.findElement(By.linkText("Customers")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Customers");
    selected = driver.findElement(By.className("selected"));
    selected.findElement(By.linkText("Customers")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Customers");
    driver.findElement(By.linkText("CSV Import/Export")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "CSV Import/Export");
    driver.findElement(By.linkText("Newsletter")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Newsletter");
    driver.findElement(By.linkText("Geo Zones")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Geo Zones");
    driver.findElement(By.linkText("Languages")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Languages");
    selected = driver.findElement(By.className("selected"));
    selected.findElement(By.linkText("Languages")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Languages");
    driver.findElement(By.linkText("Storage Encoding")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Storage Encoding");
     driver.findElement(By.linkText("Modules")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Job Modules");
    driver.findElement(By.linkText("Background Jobs")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Job Modules");
    driver.findElement(By.linkText("Customer")).click();
  assertEquals(driver.findElement(By.tagName("h1")).getText(), "Customer Modules");
    driver.findElement(By.linkText("Shipping")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Shipping Modules");
    driver.findElement(By.linkText("Payment")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Payment Modules");
    driver.findElement(By.linkText("Order Total")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Order Total Modules");
    driver.findElement(By.linkText("Order Success")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Order Success Modules");
    driver.findElement(By.linkText("Order Action")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Order Action Modules");
    driver.findElement(By.linkText("Orders")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Orders");
    selected = driver.findElement(By.className("selected"));
    selected.findElement(By.linkText("Orders")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Orders");
    driver.findElement(By.linkText("Order Statuses")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Order Statuses");
    driver.findElement(By.linkText("Pages")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Pages");
    driver.findElement(By.linkText("Reports")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Monthly Sales");
    driver.findElement(By.linkText("Monthly Sales")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Monthly Sales");
    driver.findElement(By.linkText("Most Sold Products")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Most Sold Products");
    driver.findElement(By.linkText("Most Shopping Customers")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Most Shopping Customers");
    driver.findElement(By.linkText("Settings")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Store Info")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Defaults")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("General")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Listings")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Images")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Checkout")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Advanced")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Security")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Settings");
    driver.findElement(By.linkText("Slides")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Slides");
    driver.findElement(By.linkText("Tax")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Tax Classes");

    driver.findElement(By.linkText("Tax Classes")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Tax Classes");
    driver.findElement(By.linkText("Tax Rates")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Tax Rates");

    driver.findElement(By.linkText("Translations")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Search Translations");
    driver.findElement(By.linkText("Search Translations")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Search Translations");
    driver.findElement(By.linkText("Scan Files")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Scan Files For Translations");
    driver.findElement(By.linkText("CSV Import/Export")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "CSV Import/Export");
    driver.findElement(By.linkText("Users")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "Users");
    driver.findElement(By.linkText("vQmods")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "vQmods");
    selected = driver.findElement(By.className("selected"));
    selected.findElement(By.linkText("vQmods")).click();
    assertEquals(driver.findElement(By.tagName("h1")).getText(), "vQmods");
  }
}
